name = "cf-dice-pages"
main = "src/worker.ts"
compatibility_date = "2024-05-01"
pages_build_output_dir = "./frontend/dist"
pages_functions_dir = "./functions"

[vars]
GOOGLE_CLIENT_ID = "465792064386-2g9rcesrhk2enbrlhg7ph4lrg106a75v.apps.googleusercontent.com"
VITE_GOOGLE_CLIENT_ID = "465792064386-2g9rcesrhk2enbrlhg7ph4lrg106a75v.apps.googleusercontent.com"

[[d1_databases]]
binding = "DB"
database_name = "dice-db"
database_id = "5b309725-f389-4581-9e58-4b4131d963a1"

[durable_objects]
bindings = [{ name = "DICE_ROOM", class_name = "DiceRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["DiceRoom"]
