name = "kruschtya-planet"
compatibility_date = "2024-05-01"
pages_build_output_dir = "./frontend/dist"
pages_functions_dir = "./functions"

[vars]
GOOGLE_CLIENT_ID = "465792064386-2g9rcesrhk2enbrlhg7ph4lrg106a75v.apps.googleusercontent.com"
VITE_GOOGLE_CLIENT_ID = "465792064386-2g9rcesrhk2enbrlhg7ph4lrg106a75v.apps.googleusercontent.com"